openapi: 3.0.3
info:
  title: DotAAS Part 2 | HTTP/REST | AASX File Server API
  description: The AASX file server API as part of Details of the Asset Administration Shell Part 2
  termsOfService: https://github.com/admin-shell-io/aas-specs
  contact:
    name: "Constantin Ziesche, Andreas Orzelski, Florian Krebs, Bastian Rössl, Manuel Sauer, Jens Vialkowitsch, Michael Hoffmeister, Torben Miny, Sebastian Bader, Marko Ristin, Nico Braunisch"
  version: V1.0RC03
servers:
- url: "{protocol}://{host_name}:{port}/api/{version_prefix}"
  variables:
    protocol:
      description: Allows access through http and https (recommended)
      default: https
      enum:
      - http
      - https
    host_name:
      description: Hostname of server hosting the api
      default: admin-shell.io
    port:
      description: "80 is default for http, 443 for https"
      default: "443"
      enum:
      - "80"
      - "443"
    version_prefix:
      default: v1
      enum:
      - v1
paths:
  /packages:
    get:
      tags:
      - AASX File Server API
      summary: Returns a list of available AASX packages at the server
      operationId: GetAllAASXPackageIds
      parameters:
      - name: aasId
        in: query
        description: The Asset Administration Shell’s unique id (UTF8-BASE64-URL-encoded)
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: byte
      responses:
        "200":
          description: Requested package list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PackageDescription"
        default:
          description: Default error handling for unmentioned status codes
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Result"
      x-semanticIds:
      - https://admin-shell.io/aas/API/GetAllAASXPackageIds/1/0/RC03
    post:
      tags:
      - AASX File Server API
      summary: Stores the AASX package at the server
      operationId: PostAASXPackage
      requestBody:
        description: AASX package
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/packages_body"
            encoding:
              file:
                contentType: application/asset-administration-shell-package
        required: true
      responses:
        "201":
          description: AASX package stored successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PackageDescription"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Result"
        default:
          description: Default error handling for unmentioned status codes
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Result"
      x-semanticIds:
      - https://admin-shell.io/aas/API/PostAASXPackage/1/0/RC03
  /packages/{packageId}:
    get:
      tags:
      - AASX File Server API
      summary: Returns a specific AASX package from the server
      operationId: GetAASXByPackageId
      parameters:
      - name: packageId
        in: path
        description: The package Id (UTF8-BASE64-URL-encoded)
        required: true
        style: simple
        explode: true
        schema:
          type: string
          format: byte
      responses:
        "200":
          description: Requested AASX package
          headers:
            X-FileName:
              description: Filename of the package
              schema:
                type: string
          content:
            application/asset-administration-shell-package:
              schema:
                type: string
                format: binary
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Result"
        default:
          description: Default error handling for unmentioned status codes
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Result"
      x-semanticIds:
      - https://admin-shell.io/aas/API/GetAASXByPackageId/1/0/RC03
    put:
      tags:
      - AASX File Server API
      summary: Updates the AASX package at the server
      operationId: PutAASXByPackageId
      parameters:
      - name: packageId
        in: path
        description: The Package Id (UTF8-BASE64-URL-encoded)
        required: true
        style: simple
        explode: true
        schema:
          type: string
          format: byte
      requestBody:
        description: AASX package
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/packages_packageId_body"
            encoding:
              file:
                contentType: application/asset-administration-shell-package
        required: true
      responses:
        "204":
          description: AASX package updated successfully
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Result"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Result"
        default:
          description: Default error handling for unmentioned status codes
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Result"
      x-semanticIds:
      - https://admin-shell.io/aas/API/PutAASXByPackageId/1/0/RC03
    delete:
      tags:
      - AASX File Server API
      summary: Deletes a specific AASX package from the server
      operationId: DeleteAASXByPackageId
      parameters:
      - name: packageId
        in: path
        description: The Package Id (UTF8-BASE64-URL-encoded)
        required: true
        style: simple
        explode: true
        schema:
          type: string
          format: byte
      responses:
        "204":
          description: Deleted successfully
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Result"
        default:
          description: Default error handling for unmentioned status codes
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Result"
      x-semanticIds:
      - https://admin-shell.io/aas/API/DeleteAASXByPackageId/1/0/RC03
components:
  schemas:
    PackageDescription:
      type: object
      properties:
        aasIds:
          type: array
          items:
            type: string
        packageId:
          type: string
    Result:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: "#/components/schemas/Message"
        success:
          type: boolean
    Message:
      type: object
      properties:
        code:
          type: string
        messageType:
          type: string
          enum:
          - Undefined
          - Info
          - Warning
          - Error
          - Exception
        text:
          type: string
        timestamp:
          type: string
    packages_body:
      type: object
      properties:
        aasIds:
          type: array
          items:
            type: string
        file:
          type: string
          format: binary
        fileName:
          type: string
    packages_packageId_body:
      type: object
      properties:
        aasIds:
          type: array
          items:
            type: string
        file:
          type: string
          format: binary
        fileName:
          type: string
